services:
  allrecipes_api:
    image: allrecipes_api
    build:
      context: .
      dockerfile: AllRecipes_API/Dockerfile
      ports:
        - "3001:3001" # Modifier les ports selon les besoins
      environment:
        - ASPNETCORE_ENVIRONMENT=Production