version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app