services:
  allrecipes_api:
    image: allrecipes_api
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "5243:5243" # Modifier les ports selon les besoins
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
